apiVersion: apps/v1
kind: Deployment
metadata:
  name: maskani-portal
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: core
      tier: backend
      type: app
      name: maskani-portal
  template:
    metadata:
      labels:
        app: core
        tier: backend
        type: app
        name: maskani-portal
    spec:
      restartPolicy: Always
      containers:
      - name: maskani-portal
        image: gcr.io/flatspad/maskani-portal:1.0.0
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          timeoutSeconds: 5
        ports:
          - containerPort: 8080
