apiVersion: apps/v1
kind: Deployment
metadata:
  name: maskani-portal
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: core
      tier: backend
      type: app
      name: maskani-portal
  template:
    metadata:
      labels:
        app: core
        tier: backend
        type: app
        name: maskani-portal
    spec:
      restartPolicy: Always
      containers:
      - name: maskani-portal
        image: gcr.io/flatspad/maskani-portal:1.0.0
        readinessProbe:
          httpGet:
            path: /#/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /#/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          timeoutSeconds: 5
        envFrom:
          - secretRef:
              name: maskani-portal-secrets
          - secretRef:
              name: cloudsql-db-credentials
        ports:
          - containerPort: 8080
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.12
        command:
          - /cloud_sql_proxy
          - -instances=flatspad:europe-west1:flatspad-prod=tcp:5432
          - -credential_file=/secrets/cloudsql/credentials.json
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials

